# Generated by Django 4.2.1 on 2024-11-13 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empId', models.IntegerField(unique=True)),
                ('empName', models.CharField(max_length=100)),
                ('phoneNumber', models.CharField(max_length=15)),
                ('emailId', models.EmailField(max_length=254)),
                ('designation', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('taskNumber', models.AutoField(primary_key=True, serialize=False)),
                ('taskName', models.CharField(default='Sample Task', max_length=100)),
                ('taskDescription', models.TextField(default='No Description')),
                ('assignedDate', models.DateField(auto_now_add=True)),
                ('deadline', models.DateField()),
                ('assignedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to='tasks.employee')),
            ],
        ),
        migrations.CreateModel(
            name='TaskAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignedDate', models.DateField(auto_now_add=True)),
                ('empId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.employee')),
                ('taskNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.task')),
            ],
        ),
        migrations.CreateModel(
            name='TaskTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('taskAssignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.taskassignment')),
            ],
        ),
    ]
