# Generated by Django 4.2.4 on 2024-11-12 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='taskDescription',
            field=models.TextField(default='No Description'),
        ),
        migrations.AlterField(
            model_name='task',
            name='taskName',
            field=models.CharField(default='Sample Task', max_length=100),
        ),
    ]
